version: '3'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "none"
    volumes:
      - ./db:/var/lib/neo4j/data
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: PUBLIC_IP
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  back:
    build:
      context: ./back/
      dockerfile: BuilderDockerfile
      args:
        - http_proxy
        - https_proxy
    ports:
      - "8002:8002"

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
    environment:
      - PORT: 8000
    ports:
      - "8000:8000"

